### ISSUE TITLE
autocommit.sh doesn't save all files

### ISSUE THREAD

**Issue by toscdesign** [EricZimmerman/VoronTools#9]
Hi,
I'm using your Script on Mainsail and I love it!

But I discovered that it doesn't save all config files.
It can be possible that I did a setting wrong, but the following Files don't get backuped:

/home/pi/mainsail-config/mainsail.cfg
/home/pi/moonraker-timelapse/klipper_macro/timelapse.cfg
/home/pi/Klipper-Adaptive-Meshing-Purging/Configuration

Is there a setting for that?
Or is there a possibility to add these files Manual to the script?

**Comment by EricZimmerman** [comment]
Look at the paths. 

They are not in your config folder

I would say you DONT want those tho, at least not mainsail etc. 

The latest versions of klipper also do adaptive meshing by default so you don't even really need kamp if you didn't want to include it going forward

You could certainly move those files into your config folder and then just change your includes but since they're not in the location where the rest of your config files are they are not going to ever be backed up by default

You could also manually add a copy command to auto commit at the top somewhere to make a copy into your config folder before the backup scripts run and then it would include them
